import Head from 'next/head'
import Header from '../components/Header'
import News from '../components/News'
import SendNovel from '../components/SendNovel'
import Footer from '../components/Footer'

const Home: React.FC = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.gstatic.com"/>
        <link href="https://fonts.googleapis.com/css2?family=Open+Sans:wght@300&family=Quicksand:wght@300&display=swap" rel="stylesheet"/> 
      </Head>
      <main>
        <Header/>
        <News/>
        <SendNovel/>
        <Footer/>
      </main>
    </div>
  )
}

export default Home
